### ISSUE TITLE
CARLsim still segfaults when ./results doesn't exist

### ISSUE THREAD

**Issue by mbeyeler** [UCI-CARL/CARLsim4#14]
CARLsim still segfaults when `./results` doesn't exist, no explanation given. Just learned this the hard way. It's a problem when running executables from subdirectories, such as `./carlsim/tests/carslim_tests`.

At the very least, check if directory exists before attempting to create a file within it. Notify the user accordingly.

Even better, make it possible to set a different save directory before `CARLsimInit` gets called.

**Comment by tingshuc** [comment]
Closed by #17
