### ISSUE TITLE
isinf and isnan functions cannot be recognized on OS X when installing CARLsim4

### ISSUE THREAD

**Issue by KarlXing** [UCI-CARL/CARLsim4#18]
This problem should be related to the difference of compilers since the code runs well on linux and windows. I write functions called isinf_xplat and isnan_xplat to replace them and it could be compiled on OS X now. The code will be tested on linux, windows and projects on OS X later.

**Comment by hkashyap** [comment]
Solved with commit 9ae61960619fbb310c49187bdbb1ad42a4e44eda
