### ISSUE TITLE
`full-no-direct' gives same result as 'full' connection

### ISSUE THREAD

**Issue by Prathyusha12** [UCI-CARL/CARLsim4#26]
The full-no-direct connection type gives the same connections as the full connection type. The control does not enter this condition in the code.(might be something that I am overlooking, please let me know)

**Comment by hkashyap** [comment]
Hey Ting, seems like the condition to check if neuron i in pre and neuron j in post group is there. 
`// if flag is set, don't connect direct connections
			if(noDirect && gPreN == gPostN)
				continue;`

line 3302 snn_manager.cpp

But I guess "gPreN == gPostN" is never satisfied

**Comment by hkashyap** [comment]
Hi Prathyusha, are you trying to connect two separate groups using "full-no-direct"? 
Ting and I discussed, and it seems "full-no-direct" is meant for making a recurrent connection within the same group, i.e. connecting neuron i to neuron j in the same group, where i != j.

**Comment by Prathyusha12** [comment]
Hi, Hirak, Indeed I was trying with two different groups as it said differently in the documentation that I have read.

**Comment by hkashyap** [comment]
Hi Prathyusha, thank you for raising the issue. We will update it the new documentation that will be released soon. After that, we will close this issue.

**Comment by hkashyap** [comment]
Solved with commit d503e01da869003438febb7dbd1055734079d7c0
