### ISSUE TITLE
Visual Studio solution does not open or build without CUDA

### ISSUE THREAD

**Issue by Malthanatos** [UCI-CARL/CARLsim4#67]
I get the following error attempting to open (never mind compile/build) the CARLsim solution file in Visual Studio:

C:\Users\USERNAME\Documents\working\CARLsim4\carlsim\kernel\carlsim.vcxproj(74,5): The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 8.0.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

I tried on VS 2015 and 2017

**Comment by hkashyap** [comment]
@tingshuc hi Ting, can you please look into this VS issue? People were trying to build carlsim.sln in the class and got these issues. Is cuda 8.0 hardcoded and how to build on Windows without GPU?

**Comment by tingshuc** [comment]
It might be the setting in VS. Right click on project and find out "Build Dependencies" > "Build Customizations" and make sure CUDA 8.0 is selected.

**Comment by hkashyap** [comment]
Another suggestion from @tingshuc 

If VS GUI can't solve the problem, another way to fix is open *.vcxproj by text editor. Make sure these two lines are set to CUDA 8.0.

<Import Project="$(VCTargetsPath)\BuildCustomizations\CUDA 8.0.props" />

<Import Project="$(VCTargetsPath)\BuildCustomizations\CUDA 8.0.targets" />
